apiVersion: v1
kind: Namespace
metadata:
  name: thomasthorntoncloud
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: thomasthornton
  namespace: thomasthorntoncloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thomasthorntoncloud
  template:
    metadata:
      labels:
        app: thomasthorntoncloud
    spec:
      containers:
      - name: thomasthorntoncloud
        image: devopsthehardwayazurecr.azurecr.io/thomasthorntoncloud:v2  # Update this line
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: thomasthorntoncloud
  namespace: thomasthorntoncloud
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: thomasthorntoncloud