# TUTORIAL WORKFLOW - NOT ACTIVE
# This workflow is part of the DevOps The Hard Way tutorial content
# It is disabled to prevent accidental runs in the tutorial repository
# Copy this to their own repositories and modify as needed

name: Terraform-Deploy (Tutorial Example)

# This workflow only runs manually and is intended as tutorial content
on:
  workflow_dispatch:
    inputs:
      tutorial_mode:
        description: 'This is a tutorial workflow - copy to your own repo to use'
        required: true
        default: 'tutorial-only'
        type: choice
        options:
          - tutorial-only

jobs:
  tutorial-info:
    name: ⚠️ Tutorial Workflow Information
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.tutorial_mode == 'tutorial-only' }}
    
    steps:
    - name: Tutorial Information
      run: |
        echo "🎓 This is a TUTORIAL workflow from DevOps The Hard Way - Azure"
        echo ""
        echo "📋 This workflow is provided as example content for learning purposes."
        echo "📋 It is not intended to run in the tutorial repository."
        echo ""
        echo "✅ To use this workflow:"
        echo "1. Copy this repository to your own GitHub account"
        echo "2. Set up Azure OIDC authentication secrets"
        echo "3. Modify the workflow for your specific needs"
        echo "4. Update the terraform.tfvars and backend configuration"
        echo ""
        echo "📚 For full instructions, see the tutorial documentation."
        echo ""
        echo "❌ This workflow will not deploy any resources in tutorial mode."

  terraform:
    name: Terraform-Deploy
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.tutorial_mode != 'tutorial-only' }}
    permissions:
      contents: write
      id-token: write  # Required for OIDC
      
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      ARM_USE_OIDC: true
      tf_resource_group_name: "thomasthorntoncloud"
      tf_storage_account_name: "thomasthorntontfstate"
      tf_state_container: "devopsthehardwaygithub"
      tf_state_key: "terraform.tfstate"


    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.9.8
        terraform_wrapper: true

    # Add in tutorial 6-Terarform-Docs
    # - name: Render terraform docs and push changes back to PR
    #   uses: terraform-docs/gh-actions@v1.3.0
    #   with:
    #     working-dir: ./2-Terraform-AZURE-Services-Creation/1-acr, ./2-Terraform-AZURE-Services-Creation/2-vnet, ./2-Terraform-AZURE-Services-Creation/3-log-analytics, ./2-Terraform-AZURE-Services-Creation/4-aks
    #     output-file: README.md
    #     output-method: inject
    #     git-push: "true"

    - name: Terraform Init
      run: terraform init
      working-directory: ./2-Terraform-AZURE-Services-Creation/4-aks
    
    # Add in tutorial 5-Terraform-Static-Code-Analysis
    # - name: tfsec
    #   uses: aquasecurity/tfsec-pr-commenter-action@v1.3.0
    #   with:
    #     tfsec_args: --soft-fail
    #     github_token: ${{ github.token }}

    - name: Terraform Format
      if: github.event_name == 'pull_request'
      run: terraform fmt
      working-directory: ./2-Terraform-AZURE-Services-Creation/4-aks

    - name: Auto Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      if: github.event_name == 'pull_request'
      with:
        commit_message: "Terraform fmt"
        file_pattern: "*.tf *.tfvars"
        commit_user_name: "github-actions[bot]"
  
    - name: Terraform Plan
      run: terraform plan -no-color -input=false
      working-directory: ./2-Terraform-AZURE-Services-Creation/4-aks
      env:
        DEPLOYMENT_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      run: terraform apply -auto-approve -input=false
      working-directory: ./2-Terraform-AZURE-Services-Creation/4-aks
